#!python

MAX_NUM_WORDS = 80000
MAX_REVIEW_LENGTH = 200
MAX_EMBEDDING_OUTPUT_DIM_LENGTH = 128
MODEL_TRAIN_BATCH_SIZE = 32
MODEL_PERSISTENT_FORMAT = "h5"
MODEL_PERSISTENT_NAME = "model_movie_reviews"
MODEL_PERSISTENT_DIR = "./"
FILE_EXT_DELIMITER = "."
BATCH_SIZE = 500
MODEL_PATH = MODEL_PERSISTENT_DIR + MODEL_PERSISTENT_NAME + FILE_EXT_DELIMITER + MODEL_PERSISTENT_FORMAT

